"""empty message

Revision ID: 5a32b7314234
Revises: 8fc1676403fd
Create Date: 2018-01-17 07:03:41.374384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a32b7314234'
down_revision = '8fc1676403fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('blog', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blog', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog', type_='foreignkey')
    op.drop_column('blog', 'author_id')
    op.drop_table('user')
    # ### end Alembic commands ###
